# News sources configuration
scrape_interval_minutes: 240
retention_days: 7

sources:
  - name: "The Race"
    url: "https://www.the-race.com/rss/"
    type: "rss"
    enabled: true

  - name: "Motorsport F1"
    url: "https://www.motorsport.com/rss/f1/news/"
    type: "rss"
    enabled: true

  - name: "Racefans"
    url: "https://www.racefans.net/feed/"
    type: "rss"
    enabled: true  

  - name: "WCCF Tech"
    url: "https://wccftech.com/feed/"
    type: "rss"
    enabled: true

  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"
    type: "rss"
    enabled: true

  - name: "Ars Technica"
    url: "https://feeds.arstechnica.com/arstechnica/index"
    type: "rss"
    enabled: true

  - name: "Videocardz"
    url: "https://videocardz.com/rss-feed"
    type: "rss"
    enabled: true

  - name: "Bleeping Computer"
    url: "https://www.bleepingcomputer.com/feed/"
    type: "rss"
    enabled: "true"

  - name: "Slashdot"
    url: "https://rss.slashdot.org/Slashdot/slashdotMain"
    type: "rss"
    enabled: "true"  



# LLM Configuration
llm:
  host: "192.168.50.27"
  port: 11434
  model: "gpt-oss:20b"